---
- name: "Install pacemaker"
  any_errors_fatal: true
  poll: 0
  shell: "yum install -y {{ item }}"
  with_items:
    - pcs
  register: packages_install
  failed_when: packages_install.rc != 0

- name: "Ensure pcsd has started and enabled on boot"
  any_errors_fatal: true
  poll: 0
  shell: "{{ item }}"
  with_items:
    - systemctl start pcsd
    - systemctl enable pcsd
  register: pcsd_enable
  failed_when: pcsd_enable.rc != 0

- pause:
    seconds: 5

- name: "Set a password for hacluster"
  any_errors_fatal: true
  poll: 0
  shell: "echo {{ ha_pass }} | passwd --stdin hacluster && sleep 1"
  register: pwd_setting
  failed_when: pwd_setting.rc != 0

- name: "Set corosync auth settings"
  any_errors_fatal: true
  poll: 0
  shell: "pcs cluster auth {{ item }} -u hacluster -p {{ ha_pass }}"
  with_items: "{{ play_hosts|join(' ') }}"
  register: cluster_auth
  failed_when: cluster_auth.rc != 0
  when: node == 1

- pause:
    seconds: 10

- name: "Create a cluster"
  any_errors_fatal: true
  poll: 0
  shell: "pcs cluster setup --start --name {{ ha_id }} {{ item }} --force"
  with_items: "{{ play_hosts|join(' ') }}"
  delegate_to: "{{ play_hosts[0] }}"
  register: cluster_setup
  failed_when: cluster_setup.rc != 0
  run_once: true

- pause:
    seconds: 15

- name: "Ensure corosync|pacemaker has started and enabled on boot"
  any_errors_fatal: true
  poll: 0
  shell: "{{ item }}"
  with_items:
    - systemctl start corosync && sleep 1
    - systemctl start pacemaker && sleep 1
    - systemctl enable corosync
    - systemctl enable pacemaker
  register: service_enable
  failed_when: service_enable.rc != 0

- name: "Check the pcs status for all nodes of the cluster are online"
  any_errors_fatal: true
  poll: 0
  shell: pcs status pcsd
  register: pcs_status
  failed_when: pcs_status.rc != 0

- name: "Check pcsd|corosync|pacemaker has running and started on boot"
  any_errors_fatal: true
  poll: 0
  shell: "pcs status | sed -n '/Daemon/,$p'"
  register: pcs_service
  failed_when: pcs_service.stdout.find('disabled') != -1

- name: "Freed target's memory usage"
  poll: 0
  shell: sync ; echo 3 > /proc/sys/vm/drop_caches
