---
- name: "Import variable file"
  poll: 0
  include_vars: "../vars/pacemaker.yml"

- name: "Create HA for the first time"
  block:
    - include: ha-centos6.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '6'
        - ha == 'ha'

    - include: ha-centos7.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '7'
        - ha == 'ha'

- name: "Use for adding extra node into the existing HA"
  block:
    - include: ha-ext-centos6.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '6'
        - ha == 'ha-ext'

    - include: ha-ext-centos7.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '7'
        - ha == 'ha-ext'
