---
  - name: Ensure OpenSSL is installed
    shell: yum install -y openssl
    tags: [ssl-certs,packages]

  - name: Ensure ssl folder exist
    file:
      path: "{{ ssl_certs_path }}"
      state: directory
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
    tags: [ssl-certs,configuration]

  - local_action: stat path={{ ssl_certs_local_key_path }}
    register: stat_privkey
    become: no
    tags: [ssl-certs,configuration]

  - local_action: stat path={{ ssl_certs_local_pem_path }}
    register: stat_cert
    become: no
    tags: [ssl-certs,configuration]

  - name: Test if privkey file is needed
    fail: msg="Privkey file {{ ssl_certs_local_key_path }} is missing"
    when: not stat_privkey.stat.exists and stat_cert.stat.exists
    tags: [ssl-certs,configuration]

  - name: Test if cert file is needed
    fail: msg="Cert file {{ ssl_certs_local_pem_path }} is missing"
    when: stat_privkey.stat.exists and not stat_cert.stat.exists
    tags: [ssl-certs,configuration]

  - include: generate.yml
    when: >
      ( not stat_privkey.stat.exists and not stat_cert.stat.exists )
      and ( ssl_certs_local_key_data == '' and ssl_certs_local_pem_data == '' )
    tags: [ssl-certs,configuration]

  - name: Copy SSL private key file (if exists)
    copy:
      src: "{{ ssl_certs_local_key_path }}"
      dest: "{{ ssl_certs_key_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
      force: "{{ ssl_certs_force_replace }}"
    when: >
      ( stat_privkey.stat.exists )
      and ( ssl_certs_local_key_data == '' )
    tags: [ssl-certs,configuration]

  - name: Copy SSL certificate file (if exists)
    copy:
      src: "{{ ssl_certs_local_pem_path }}"
      dest: "{{ ssl_certs_pem_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
      force: "{{ ssl_certs_force_replace }}"
    when: >
      ( stat_cert.stat.exists )
      and ( ssl_certs_local_pem_data == '' )
    tags: [ssl-certs,configuration]

  - name: Copy SSL certificate data
    copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
      force: "{{ ssl_certs_force_replace }}"
    when: item.content != ''
    with_items:
      - { content: "{{ ssl_certs_local_pem_data|default }}", dest: "{{ ssl_certs_pem_path }}" }
      - { content: "{{ ssl_certs_local_key_data|default }}", dest: "{{ ssl_certs_key_path }}" }
    no_log: true
    tags: [ssl-certs,configuration]

  - name: Generate strong DHE parameter - https://weakdh.org/
    command: openssl dhparam -dsaparam -out {{ssl_certs_dhparam_path}} {{ssl_certs_dhparam_size}} creates={{ssl_certs_dhparam_path}}
    when: ssl_certs_generate_dh_param
    tags: [ssl-certs,configuration]

  - name: Combine key and cert
    assemble:
      dest: "{{ ssl_certs_combined_path }}"
      src: "{{ ssl_certs_path }}"
      regexp: "({{ (ssl_certs_key_path | basename) | regex_escape }}|{{ (ssl_certs_pem_path | basename) | regex_escape }})"
    tags: [ssl-certs,configuration]

  - include: comparefile.yml 
