---
  - name: Generate RSA key
    command: "openssl genrsa -out {{ ssl_certs_key_path }} {{ ssl_certs_key_size }}"
    args:
      creates: "{{ ssl_certs_key_path }}"

  - name: RSA key file ownership
    file:
      path: "{{ ssl_certs_key_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"

  - name: Generate certificate config file
    template:
      src: sslcert.conf.j2
      dest: "{{ ssl_certs_conf_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"

  - name: Generate CSR
    command: "openssl req -config {{ ssl_certs_conf_path }} -new -sha256 -key {{ ssl_certs_key_path }} -out {{ ssl_certs_csr_path }}"
    args:
      creates: "{{ ssl_certs_csr_path }}"

  - name: CSR file ownership
    file:
      path: "{{ ssl_certs_csr_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"

  - name: Generate self-signed SSL certificate
    command: "openssl req -config {{ ssl_certs_conf_path }} -nodes -x509 -sha256 -days {{ ssl_certs_days }} -in {{ ssl_certs_csr_path }} -key {{ ssl_certs_key_path }} -out {{ ssl_certs_pem_path }} -extensions v3_ca"
    args:
      creates: "{{ ssl_certs_pem_path }}"
    when: ssl_certs_generate_self_signed

  - name: Self-signed SSL certificate file ownership
    file:
      path: "{{ ssl_certs_pem_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
    when: ssl_certs_generate_self_signed

  - name: Generate CRT file
    command: "openssl x509 -outform pem -in {{ ssl_certs_pem_path }} -out {{ ssl_certs_crt_path }}"
    args:
      creates: "{{ ssl_certs_crt_path }}"

  - name: CRT file ownership
    file:
      path: "{{ ssl_certs_crt_path }}"
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
