---
- name: "Install NTP"
  any_errors_fatal: true
  poll: 0
  shell: yum install -y ntp
  register: ntp_install
  failed_when: ntp_install.rc != 0

- name: "Deploy NTP configuration"
  any_errors_fatal: true
  poll: 0
  template: "{{ item }}"
  with_items:
    - { src: "./ntp-server/templates/ntp.conf.j2" , dest: "/etc/ntp.conf" , mode: "0644" }
  register: ntp_config
  failed_when: ntp_config.state != 'file'

- name: "Enable ntpd"
  any_errors_fatal: true
  block:
    - shell: "{{ item }}"
      with_items:
        - service ntpd start
        - chkconfig ntpd on
      register: ntpd_enable
      failed_when: ntpd_enable.rc != 0
      when: ansible_distribution_major_version == '6'
    - shell: "{{ item }}"
      with_items:
        - systemctl start ntpd
        - systemctl enable ntpd
      register: ntpd_enable
      failed_when: ntpd_enable.rc != 0
      when: ansible_distribution_major_version == '7'

- name: "Check ntpd"
  any_errors_fatal: true
  block:
    - shell: "{{ item }}"
      with_items:
        - service ntpd status
        - chkconfig --list ntpd | grep on
      register: ntpd_check
      failed_when: ntpd_check.rc != 0
      when: ansible_distribution_major_version == '6'
    - shell: "{{ item }}"
      with_items:
        - systemctl status ntpd
        - systemctl list-unit-files | grep -w ntpd | grep enabled
      register: ntpd_check
      failed_when: ntpd_check.rc != 0
      when: ansible_distribution_major_version == '7'

- name: "Reload ntpd"
  any_errors_fatal: true
  block:
    - shell: service ntpd force-reload
      register: ntpd_reload
      failed_when: ntpd_reload.rc != 0
      when:
        - ntp_config.changed
        - ansible_distribution_major_version == '6'
    - shell: systemctl force-reload ntpd
      register: ntpd_reload
      failed_when: ntpd_reload.rc != 0
      when:
        - ntp_config.changed
        - ansible_distribution_major_version == '7'

- name: "Check NTP server sync"
  any_errors_fatal: true
  poll: 0
  shell: "ntpdate -q {{ item }}"
  with_items:
    - "{{ ntp_server[0] }}"
    - "{{ ntp_server[1] }}"
  register: ntp_sync
  failed_when: ntp_sync.rc != 0
  when: ntp_config.changed

- name: "Freed target's memory usage"
  poll: 0
  shell: sync ; echo 3 > /proc/sys/vm/drop_caches
