---
- name: Get all the existing uid
  any_errors_fatal: true
  shell: "ldapsearch -h {{ ldapserver }} -x -D {{ binddn }} -w {{ bindpw }} -b {{ dn }} \
          | grep -i 'uidnumber'|cut -d ' ' -f 2"
  register: alluid
  failed_when: alluid.rc != 0

- name: "set var"
  set_fact:
    uidfact: "{{ alluid.stdout_lines }}"

- name: "Create array for uidrange"
  set_fact:
    uidrange: "[{% for index in range(1200,1500) %}'{{ index }}',{% endfor %}]"

- name: "Set uidnumber of uidrange difference uidfact"
  set_fact:
    uidnumber: "{{ uidrange | difference(uidfact) }}"

- name: "Create a template file of ldap entry ldif file"
  template:
    src: "templates/{{ ldif_temp }}"
    dest: "/tmp/{{ldif_temp|regex_replace(".*/","")|regex_replace("\.j2$","")}}"

- name: "Import new ldap entry data to ldap server"
  any_errors_fatal: true
  shell: "ldapadd -h {{ ldapserver }} -x -c -D {{ binddn }} -w {{ bindpw }} \
          -f /tmp/{{ldif_temp|regex_replace(".*/","")|regex_replace("\.j2$","")}}"
  register: import
  failed_when: import.rc != 0

- name: "Verify new ldap entry has been added"
  any_errors_fatal: true
  shell: id jjlee
  delegate_to: 192.168.43.166
