- name: Remove the ldap entry
  ldap_entry:
    dn: "cn={{ item }},{{ dn }}"
    objectClass: organizationalUnit
    bind_dn: "{{ binddn }}"
    bind_pw: "{{ bindpw }}"
    server_uri: "{{ serveruri }}"
    state: absent
  with_items:
    - "{{ absent_users }}"

- name: "Get all of existing the ldap entry"
  any_errors_fatal: true
  shell: "ldapsearch -h {{ ldapserver }} -x -D {{ binddn }} -w {{ bindpw }} -b {{ dn }} \
          | grep -i 'cn:'|cut -d ' ' -f 2"
  register: allentry
  failed_when: allentry.rc != 0

- name: "Verify the ldap entry has been removed"
  any_errors_fatal: true
  shell: "echo {{ allentry.stdout_lines }} | grep -w '{{ item }}'"
  with_items:
    - "{{ absent_users }}"
  register: verify
  failed_when: verify.rc == 0
