---
- name: "Import variable file"
  poll: 0
  include_vars: "./vars/gluster.yml"

- name: "Use to create HA for the first time"
  block:
    - include: centos7.yml
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '7'

#- name: "Use for adding extra node into the existing HA"
#  block:
#   - include: ext-centos7.yml
#      when:
#        - ansible_distribution == CentOS
#        - ansible_distribution_major_version == '7'
