---
- name: Check python install
  any_errors_fatal: true
  poll: 0
  shell: "{{ item }}"
  with_items:
    - python2 -V
    - python3 -V
  register: py_check
  failed_when: py_check.rc != 0

- name: Check pip install
  any_errors_fatal: true
  poll: 0
  shell: "{{ item }}"
  with_items:
    - pip2 -V
  register: pip_check
  failed_when: pip_check.rc != 0

- name: Install ngxtop
  any_errors_fatal: true
  block:
    - shell: "{{ item }}"
      with_items:
        - pip2 install --upgrade pip
        - pip2 install ngxtop
      register: install
      failed_when: install.rc != 0
    - shell: ngxtop --version
      register: check
      failed_when: check.rc != 0
