---
ssl_certs_country: "TW"
ssl_certs_locality: "Taiwan"
ssl_certs_organization: "itzxa.local"
ssl_certs_state: "Taipei"
ssl_certs_common_name: "*.itzxa.local"
ssl_certs_san_name: "gitlab.itzxa.local"
ssl_certs_email: "itzxadmin@gmail.com"
ssl_certs_days: "{{ days }}"
ssl_certs_fields: "/C={{ ssl_certs_country }}/ST={{ ssl_certs_state }}/L={{ ssl_certs_locality }}/O={{ ssl_certs_organization }}/CN={{ ssl_certs_common_name }}"

ssl_certs_path: "{{ playbook_dir }}/{{ ssl_certs_organization }}"
ssl_certs_conf_path: "{{ ssl_certs_path }}/{{ ssl_certs_san_name }}.conf"
ssl_certs_path_owner: "{{ owner }}"
ssl_certs_path_group: "{{ owner }}"
ssl_certs_key_path: "{{ ssl_certs_path }}/{{ ssl_certs_san_name }}.key"
ssl_certs_pem_path: "{{ ssl_certs_path }}/{{ ssl_certs_san_name }}.pem"
ssl_certs_csr_path: "{{ ssl_certs_path }}/{{ ssl_certs_san_name }}.csr"
ssl_certs_crt_path: "{{ ssl_certs_path }}/{{ ssl_certs_san_name }}.crt"
ssl_certs_combined_path: "{{ ssl_certs_path }}/{{ ssl_certs_san_name }}.combined.pem"
ssl_certs_dhparam_path: "{{ ssl_certs_path }}/dhparam.pem"
ssl_certs_mode: "0755"
ssl_certs_force_replace: yes

ssl_certs_local_key_path: "{{ inventory_dir|default(playbook_dir) }}/files/ssl/{{ ssl_certs_san_name}}.key"
ssl_certs_local_pem_path: "{{ inventory_dir|default(playbook_dir) }}/files/ssl/{{ ssl_certs_san_name }}.pem"
ssl_certs_local_key_data: ""
ssl_certs_local_pem_data: ""

ssl_certs_generate_self_signed: true
ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: false
ssl_certs_dhparam_size: "2048"
